# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import scoremanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreboardEntry',
            fields=[
                ('identifier', models.CharField(default=scoremanager.models.identifier_default, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.PositiveIntegerField()),
                ('balls_dropped', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-score', 'balls_dropped', 'date_created'],
            },
        ),
    ]
